version: 2
jobs:
  build:
    parallelism: 1
    resource_class: small
    working_directory: "~/bai2"
    docker:
    - image: 207583270433.dkr.ecr.us-west-1.amazonaws.com/universe/ruby_24:0.15
    steps:
      - checkout
      - run:
          name: build gem
          command: |
            gem build bai2.gemspec
      - run:
          name: push gem
          command: |
            if [[ -n "${GEMFURY_USERNAME}" && -n "${GEMFURY_PASSWORD}" ]]; then
              echo -e "machine api.fury.io\n  login ${GEMFURY_USERNAME}\n  password ${GEMFURY_PASSWORD}" >> ~/.netrc
              chmod 600 ~/.netrc
              version=$(parse-gemspec-cli bai2.gemspec | jq -r ".version")
              grep -q "${version}" <(fury versions bai2) || EXIT_CODE=$? && true
              if [[ $EXIT_CODE == 1 ]]; then
                fury push bai2-${version}.gem
              else
                echo "bai2 version ${version} has previously been released to gemfury, increment the version for a new release"
              fi
            fi
workflows:
  version: 2
  build-and-push:
    jobs:
    - build:
        context: org-global
        filters:
          branches:
            only: master
